---
- name: enable firewall d service
  service:
    name: "{{ firewall_service_name }}"
    state: started
    enabled: true
  become: true
  when: ansible_facts['os_family'] == "RedHat"
  notify: reload firewall