---
- hosts: all
  become: true
  tasks:
    - name: Install tomcat
      yum:
        name: tomcat
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: Install tomcat in cent
      dnf:
        name: tomcat
        state: present
      when: ansible_facts['os_family'] == "CentOS"