---
- name: Copying files
  hosts: all
  become: true
  tasks:
    - name: Copy a file to the remote server
      copy:
        src: /home/ansible/imp_file.txt
        dest: /tmp
        owner: ansible
        group: ansible
        mode: '0644'
        backup: yes
    - name: Create a director with file bulletin
      ansible.builtin.file:
        path: /tmp/new
        state: directory
        mode: '0755' 
       


