---
- name: Firewall changes
  hosts: all
  become: true
  tasks:
  - name: Ensure firewalld service is enabled and running
    service:
      name: firewalld
      state: started
      enabled: true
    register: firewalld_service

  - name: Open port 80 for HTTP
    ansible.posix.firewalld:
      service: http
      state: enabled
      permanent: true
      immediate: true
    register: firewalld_http

  - name: Reload firewalld if changes were made
    ansible.posix.firewalld:
      state: reloaded
    when: firewalld_service.changed or firewalld_http.changed