--- 
- hosts: all
  become: true
  tasks:
    - name: Firewall reload
      firewalld:
        port: 8081/tcp
        permanent: true
        state: enabled
      notify: Restart firewalld

  handlers:
    - name: Restart firewalld
      service:
        state: reloaded

       