---
- name: Simple playbook using secret key
  hosts: all
  become: true
  vars_files:
    - ../group_vars/all/vault.yml

  tasks:
    - name: Create config directory
      file:
        path: /opt/myapp
        state: directory
        mode: '0755'

    - name: Write secret key to file
      copy:
        content: "SECRET_KEY={{ my_secret_key }}"
        dest: /opt/myapp/secret.conf
        owner: root
        group: root
        mode: '0600'

    - name: Show secret key (for debug only)
      debug:
        msg: "The secret key is {{ my_secret_key }}"
