---
- hosts: all
  become: true
  vars:
    app: nginx
  tasks:
    - name: Install Nginx
      dnf:
        name: "{{ app }}"
        state: present
      tags: install_nginx

    - name: Start Nginx service
      service:
        name: "{{ app }}"
        state: started
        enabled: true
      tags: nginx_start
